import type { RoleSuggestion } from "@domain";
import { describeError, Skeleton } from "@web/components/ui";
import type { RoleSuggestionResponse } from "@web/lib/profile";
import {
  fetchRoleSuggestions,
  generateRoleSuggestions,
} from "@web/lib/profile";
import { Loader2, RefreshCw, Sparkles } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";

/**
 * Titles the agent thinks this resume is already qualified for, as searches.
 *
 * The search box assumes the user knows what to type, which is the one thing a
 * career change or a first job does not come with. These are the agent's
 * answer to "what am I?" — read off the stored profile, so a machine with no
 * saved resume renders nothing at all rather than guessing from the committed
 * seed.
 *
 * Generation costs a model call, so the stored set is read first and paid for
 * only when the profile behind it changed. That is also why the row stays
 * visible while a refresh is in flight: last week's suggestions are still
 * usable, and blanking them would make an edit look like a failure.
 */

function Chip({
  suggestion,
  active,
  onPick,
}: {
  suggestion: RoleSuggestion;
  active: boolean;
  onPick: (query: string) => void;
}) {
  return (
    <li className="flex shrink-0">
      <button
        type="button"
        // The reason is the evidence for the suggestion; it is too long for the
        // chip and too load-bearing to drop, so it rides on the accessible name
        // and the tooltip rather than in a second line of text.
        title={suggestion.reason}
        aria-label={
          suggestion.reason
            ? `Search ${suggestion.title} — ${suggestion.reason}`
            : `Search ${suggestion.title}`
        }
        aria-pressed={active}
        data-testid={`role-suggestion-${suggestion.query}`}
        className={`u-mono inline-flex items-center gap-1.5 rounded-xs border px-2 py-1 whitespace-nowrap focus:outline-1 focus:outline-signal ${
          active
            ? "border-signal bg-signal/10 text-ink"
            : "border-ridge-hi bg-panel-hi text-ink-dim hover:border-signal hover:text-ink"
        }`}
        onClick={() => onPick(suggestion.query)}
      >
        {suggestion.title}
      </button>
    </li>
  );
}

export function RoleSuggestions({
  activeQuery,
  onPick,
}: {
  /** The search text currently in the URL, so a picked chip reads as picked. */
  activeQuery: string;
  onPick: (query: string) => void;
}) {
  const [state, setState] = useState<RoleSuggestionResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const run = useRef<AbortController | null>(null);
  /** One automatic generation per mount; the button owns every one after it. */
  const autoGenerated = useRef(false);

  const generate = useCallback(() => {
    run.current?.abort();
    const controller = new AbortController();
    run.current = controller;
    setGenerating(true);
    setError(null);

    void (async () => {
      try {
        setState(await generateRoleSuggestions(controller.signal));
      } catch (cause) {
        if (controller.signal.aborted) return;
        setError(describeError(cause));
      } finally {
        if (!controller.signal.aborted) setGenerating(false);
      }
    })();
  }, []);

  useEffect(() => {
    const controller = new AbortController();
    run.current = controller;

    void (async () => {
      try {
        const answer = await fetchRoleSuggestions(controller.signal);
        if (controller.signal.aborted) return;
        setState(answer);
        setLoading(false);
        if (
          answer.profileSource === "stored" &&
          answer.stale &&
          !autoGenerated.current
        ) {
          autoGenerated.current = true;
          generate();
        }
      } catch (cause) {
        if (controller.signal.aborted) return;
        setError(describeError(cause));
        setLoading(false);
      }
    })();

    return () => controller.abort();
  }, [generate]);

  // No saved resume means there is nothing to suggest from, and a row that
  // explains its own emptiness would be louder than the feature is worth: the
  // profile screen is where that is already said.
  if (loading || state === null || state.profileSource === "seed") return null;

  const suggestions = state.suggestions;
  if (suggestions.length === 0 && !generating && error === null) return null;

  return (
    <section
      aria-label="Suggested roles from your resume"
      className="flex flex-wrap items-center gap-x-3 gap-y-2"
    >
      <p className="u-mono inline-flex shrink-0 items-center gap-1.5 text-[12.5px] text-ink-dim">
        <Sparkles className="size-3.5 text-signal" aria-hidden />
        Suggested for you
      </p>

      {suggestions.length > 0 ? (
        // `flex-1` with `min-w-0`: without both, the list keeps its full
        // content width as a flex item and the chips spill over the row
        // instead of wrapping inside it.
        <ul className="flex min-w-0 flex-1 flex-wrap items-center gap-1.5">
          {suggestions.map((suggestion) => (
            <Chip
              key={suggestion.query}
              suggestion={suggestion}
              active={
                activeQuery.trim().toLowerCase() ===
                suggestion.query.toLowerCase()
              }
              onPick={onPick}
            />
          ))}
        </ul>
      ) : null}

      {generating && suggestions.length === 0 ? (
        <span className="flex items-center gap-1.5" aria-live="polite">
          <span className="sr-only">Reading your resume…</span>
          <Skeleton className="h-6 w-28" />
          <Skeleton className="h-6 w-36" />
          <Skeleton className="h-6 w-24" />
        </span>
      ) : null}

      <button
        type="button"
        className="btn"
        disabled={generating}
        onClick={generate}
      >
        {generating ? (
          <Loader2 className="size-3.5 animate-spin" aria-hidden />
        ) : (
          <RefreshCw className="size-3.5" aria-hidden />
        )}
        {generating ? "Reading resume…" : "Suggest roles"}
      </button>

      {error ? (
        <output className="u-mono text-[12.5px] text-alarm">{error}</output>
      ) : null}
    </section>
  );
}
