/**
 * Country code -> macro region, in five coarse buckets.
 *
 * A region filter exists to answer one question — "is this job on my
 * continent?" — and five buckets answer it. A finer split would hand the facet
 * rail rows that no posting text can support: boards publish a city and a
 * country, rarely a subregion, so a "Nordic" filter would sit at zero while
 * its coarse parent held all the demand.
 */

import type { JobRegion } from "@domain";

/**
 * Committed as a literal rather than derived at runtime: no Node or ICU API
 * places a country on a continent (`Intl.DisplayNames` names a code, it does
 * not place one), the grouping below carries judgment calls no standards
 * source ships, and alpha-2 assignments are near-frozen, so the table will not
 * churn. Alphabetical within each region, so a duplicate or a gap shows up in
 * review.
 */
const REGION_BY_COUNTRY: Record<string, JobRegion> = {
  // Continental split, not the linguistic one: MX belongs to the continent a
  // candidate means by "North American roles", not to the language family.
  BM: "north_america",
  CA: "north_america",
  GL: "north_america",
  MX: "north_america",
  PM: "north_america",
  US: "north_america",

  // Central America, the Caribbean, and South America — by geography, whatever
  // flag flies over the island (hence the French and Dutch territories here).
  AG: "latam",
  AI: "latam",
  AR: "latam",
  AW: "latam",
  BB: "latam",
  BL: "latam",
  BO: "latam",
  BQ: "latam",
  BR: "latam",
  BS: "latam",
  BZ: "latam",
  CL: "latam",
  CO: "latam",
  CR: "latam",
  CU: "latam",
  CW: "latam",
  DM: "latam",
  DO: "latam",
  EC: "latam",
  FK: "latam",
  GD: "latam",
  GF: "latam",
  GP: "latam",
  GT: "latam",
  GY: "latam",
  HN: "latam",
  HT: "latam",
  JM: "latam",
  KN: "latam",
  KY: "latam",
  LC: "latam",
  MF: "latam",
  MQ: "latam",
  MS: "latam",
  NI: "latam",
  PA: "latam",
  PE: "latam",
  PR: "latam",
  PY: "latam",
  SR: "latam",
  SV: "latam",
  SX: "latam",
  TC: "latam",
  TT: "latam",
  UY: "latam",
  VC: "latam",
  VE: "latam",
  VG: "latam",
  VI: "latam",

  // Europe, all of Africa, and the Middle East. The Caucasus (AM, AZ, GE) sits
  // west of the apac boundary and every EMEA board includes it; XK is Kosovo's
  // de facto code, unassigned by ISO but emitted by boards all the same.
  AD: "emea",
  AE: "emea",
  AL: "emea",
  AM: "emea",
  AO: "emea",
  AT: "emea",
  AX: "emea",
  AZ: "emea",
  BA: "emea",
  BE: "emea",
  BF: "emea",
  BG: "emea",
  BH: "emea",
  BI: "emea",
  BJ: "emea",
  BW: "emea",
  BY: "emea",
  CD: "emea",
  CF: "emea",
  CG: "emea",
  CH: "emea",
  CI: "emea",
  CM: "emea",
  CV: "emea",
  CY: "emea",
  CZ: "emea",
  DE: "emea",
  DJ: "emea",
  DK: "emea",
  DZ: "emea",
  EE: "emea",
  EG: "emea",
  EH: "emea",
  ER: "emea",
  ES: "emea",
  ET: "emea",
  FI: "emea",
  FO: "emea",
  FR: "emea",
  GA: "emea",
  GB: "emea",
  GE: "emea",
  GG: "emea",
  GH: "emea",
  GI: "emea",
  GM: "emea",
  GN: "emea",
  GQ: "emea",
  GR: "emea",
  GW: "emea",
  HR: "emea",
  HU: "emea",
  IE: "emea",
  IL: "emea",
  IM: "emea",
  IQ: "emea",
  IR: "emea",
  IS: "emea",
  IT: "emea",
  JE: "emea",
  JO: "emea",
  KE: "emea",
  KM: "emea",
  KW: "emea",
  LB: "emea",
  LI: "emea",
  LR: "emea",
  LS: "emea",
  LT: "emea",
  LU: "emea",
  LV: "emea",
  LY: "emea",
  MA: "emea",
  MC: "emea",
  MD: "emea",
  ME: "emea",
  MG: "emea",
  MK: "emea",
  ML: "emea",
  MR: "emea",
  MT: "emea",
  MU: "emea",
  MW: "emea",
  MZ: "emea",
  NA: "emea",
  NE: "emea",
  NG: "emea",
  NL: "emea",
  NO: "emea",
  OM: "emea",
  PL: "emea",
  PS: "emea",
  PT: "emea",
  QA: "emea",
  RE: "emea",
  RO: "emea",
  RS: "emea",
  RU: "emea",
  RW: "emea",
  SA: "emea",
  SC: "emea",
  SD: "emea",
  SE: "emea",
  SH: "emea",
  SI: "emea",
  SJ: "emea",
  SK: "emea",
  SL: "emea",
  SM: "emea",
  SN: "emea",
  SO: "emea",
  SS: "emea",
  ST: "emea",
  SY: "emea",
  SZ: "emea",
  TD: "emea",
  TG: "emea",
  TN: "emea",
  TR: "emea",
  TZ: "emea",
  UA: "emea",
  UG: "emea",
  VA: "emea",
  XK: "emea",
  YE: "emea",
  YT: "emea",
  ZA: "emea",
  ZM: "emea",
  ZW: "emea",

  // Asia east of and including Afghanistan and Pakistan, plus Central Asia.
  // IO has no population and no posts; it files here rather than nowhere.
  AF: "apac",
  BD: "apac",
  BN: "apac",
  BT: "apac",
  CN: "apac",
  HK: "apac",
  ID: "apac",
  IN: "apac",
  IO: "apac",
  JP: "apac",
  KG: "apac",
  KH: "apac",
  KP: "apac",
  KR: "apac",
  KZ: "apac",
  LA: "apac",
  LK: "apac",
  MM: "apac",
  MN: "apac",
  MO: "apac",
  MV: "apac",
  MY: "apac",
  NP: "apac",
  PH: "apac",
  PK: "apac",
  SG: "apac",
  TH: "apac",
  TJ: "apac",
  TL: "apac",
  TM: "apac",
  TW: "apac",
  UZ: "apac",
  VN: "apac",

  // Australia, New Zealand, and the Pacific. The subantarctic territories
  // (AQ, BV, TF, GS, HM) and the stray ocean islands (CC, CX, UM) will never
  // carry a posting; they file here rather than nowhere so the table stays
  // total — every ISO-assigned code resolves.
  AQ: "oceania",
  AS: "oceania",
  AU: "oceania",
  BV: "oceania",
  CC: "oceania",
  CK: "oceania",
  CX: "oceania",
  FJ: "oceania",
  FM: "oceania",
  GS: "oceania",
  GU: "oceania",
  HM: "oceania",
  KI: "oceania",
  MH: "oceania",
  MP: "oceania",
  NC: "oceania",
  NF: "oceania",
  NR: "oceania",
  NU: "oceania",
  NZ: "oceania",
  PF: "oceania",
  PG: "oceania",
  PN: "oceania",
  PW: "oceania",
  SB: "oceania",
  TF: "oceania",
  TK: "oceania",
  TO: "oceania",
  TV: "oceania",
  UM: "oceania",
  VU: "oceania",
  WF: "oceania",
  WS: "oceania",
};

/** ISO alpha-2 to macro region, or null when the code is not one we know. */
export function regionForCountry(code: string | null): JobRegion | null {
  if (!code) return null;
  return REGION_BY_COUNTRY[code.toUpperCase()] ?? null;
}
